# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'explore-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for explore-ios
   pod 'Alamofire', '~> 4.3.0'
   pod 'Charts'
   pod 'Firebase/Core'
   pod 'Firebase/Auth'
   pod 'Firebase/Database'
   pod 'PromiseKit', '~> 4.0'
   pod 'TwitterKit'
   pod 'MBProgressHUD', '~> 1.1.0'
end
